In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn import preprocessing
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM
from keras.models import Sequential
from keras import metrics

Using TensorFlow backend.
e:\envs\python36env\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
e:\envs\python36env\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
e:\envs\python36env\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
e:\envs\python36env\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning:

In [2]:
data_xls = pd.read_excel('辽宁钢铁行业月用电量.xls')

In [3]:
data_xls

月份  辽宁钢铁行业月用电量（亿千万时）    钢铁产量   汽车产量      水泥产量  金属切削机床   大中型拖拉机  \
0    2007M01         13.856687  354.62  78.72   8370.22    4.12  14440.0   
1    2007M02         11.941298  318.87  59.65   6500.82    3.35  13941.0   
2    2007M03         14.555307  368.91  88.96   9308.57    4.78  26231.0   
3    2007M04         13.656541  366.22  83.98  11643.56    5.41  22263.0   
4    2007M05         13.143799  374.81  74.35  12869.06    5.34  14824.0   
..       ...               ...     ...    ...       ...     ...      ...   
153  2019M10         19.591677  609.31    NaN       NaN     NaN      NaN   
154  2019M11         21.042283  630.76    NaN       NaN     NaN      NaN   
155  2019M12         21.137609  648.00    NaN       NaN     NaN      NaN   
156  2020M01         22.502425  621.00    NaN       NaN     NaN      NaN   
157  2020M02         19.675281  525.78    NaN       NaN     NaN      NaN   

      鞍钢股价   本钢股价   凌钢股价  
0    12.95   6.50   6.10  
1    12.87   8.09   7.58  
2    14.57   8.55   8.28  
3    17.64  13.35  11.03  
4    18.34  13.89  10.44  
..     ...    ...    ...  
153    NaN    NaN    NaN  
154    NaN    NaN    NaN  
155    NaN    NaN    NaN  
156    NaN    NaN    NaN  
157    NaN    NaN    NaN  

[158 rows x 10 columns]

In [4]:
# data_xls.drop(['月份'], axis=1, inplace=True)
# data_xls

In [5]:
data_origin = np.array(data_xls)[:,1]

In [6]:
data_origin

array([13.85668698, 11.94129775, 14.5553069, 13.65654085, 13.14379943,
       13.89728023, 13.82012254, 13.79591637, 13.98148773, 13.27588781,
       13.96807882, 14.28233571, 14.25003836, 12.63311045, 13.46243023,
       12.66591199, 15.74872233, 13.96355619, 14.0412472, 14.73483898,
       14.43095576, 13.07001702, 11.2565999, 12.75663418, 15.18040114,
       13.37540347, 14.73297642, 15.78046701, 17.72041254, 17.83488148,
       18.58404608, 20.17703177, 18.09534907, 18.75590088, 18.23257587,
       19.43319581, 21.23330098, 16.1386489, 19.02165091, 19.05428623,
       19.68678322, 19.79838388, 19.47129446, 21.33109174, 21.66244321,
       21.55903074, 21.76134192, 21.32224764, 23.88102624, 20.37005115,
       22.57014853, 22.31149827, 23.46213236, 23.0468898, 23.68748431,
       23.21969118, 22.34132092, 22.57994124, 20.77764555, 21.62859336,
       20.60581298, 19.12035023, 21.83852119, 22.03478112, 22.96754631,
       21.99876057, 24.83276378, 21.62148723, 20.27768634, 22.6320425

In [7]:
# #Max-Min标准化
# #建立MinMaxScaler对象
scaler = preprocessing.MinMaxScaler()

# # 标准化处理
# scaler = preprocessing.StandardScaler()

data = scaler.fit_transform(np.array(data_xls)[:,1].reshape(-1, 1))

data

array([[0.17352158],
       [0.04569457],
       [0.22014526],
       [0.16016446],
       [0.12594572],
       [0.17623064],
       [0.17108138],
       [0.16946594],
       [0.18185039],
       [0.13476088],
       [0.18095552],
       [0.20192803],
       [0.19977261],
       [0.09186396],
       [0.14721013],
       [0.09405303],
       [0.29979003],
       [0.18065369],
       [0.18583854],
       [0.23212666],
       [0.21184646],
       [0.12102172],
       [0.        ],
       [0.10010754],
       [0.26186207],
       [0.14140224],
       [0.23200236],
       [0.30190857],
       [0.43137439],
       [0.43901368],
       [0.48901056],
       [0.59532138],
       [0.45639647],
       [0.5004796 ],
       [0.46555455],
       [0.54568012],
       [0.66581344],
       [0.32581249],
       [0.51821492],
       [0.5203929 ],
       [0.56260374],
       [0.57005162],
       [0.54822271],
       [0.67233969],
       [0.69445304],
       [0.68755161],
       [0.70105322],
       [0.671

In [8]:
data.shape

(158, 1)

In [9]:
data = data[:156,:]

In [10]:
data.shape

(156, 1)

In [11]:
# n = 0
# for i in range(data.shape[0]):
#     if data[i,0]<0:
#         n=n+1
# print(n)

In [12]:
# data_y = data[-146:-2,:]
# print(data_y.shape)

In [13]:
data_x = []
for r in range(133):
    for c in range(12):
        item = []
        item.append(data[r+c, 0])
        data_x.append(item)
data_x = np.array(data_x)
print(data_x)
print(data_x.shape)

[[0.17352158]
 [0.04569457]
 [0.22014526]
 ...
 [0.66968399]
 [0.72938174]
 [0.86360998]]
(1596, 1)


In [14]:
data_x=data_x.reshape(133,12,1)

In [15]:
data_x.shape

(133, 12, 1)

In [16]:
data_x

array([[[0.17352158],
        [0.04569457],
        [0.22014526],
        ...,
        [0.13476088],
        [0.18095552],
        [0.20192803]],

       [[0.04569457],
        [0.22014526],
        [0.16016446],
        ...,
        [0.18095552],
        [0.20192803],
        [0.19977261]],

       [[0.22014526],
        [0.16016446],
        [0.12594572],
        ...,
        [0.20192803],
        [0.19977261],
        [0.09186396]],

       ...,

       [[0.68724203],
        [0.92764034],
        [0.86035021],
        ...,
        [0.70547672],
        [0.62259383],
        [0.66968399]],

       [[0.92764034],
        [0.86035021],
        [0.58780241],
        ...,
        [0.62259383],
        [0.66968399],
        [0.72938174]],

       [[0.86035021],
        [0.58780241],
        [0.62685057],
        ...,
        [0.66968399],
        [0.72938174],
        [0.86360998]]])

In [17]:
data_y = []
for r in range(12,145):
    for c in range(12):
        item = []
        item.append(data[r+c, 0])
        data_y.append(item)
data_y = np.array(data_y)
print(data_y)
print(data_y.shape)

[[0.19977261]
 [0.09186396]
 [0.14721013]
 ...
 [0.55625664]
 [0.65306548]
 [0.65942727]]
(1596, 1)


In [18]:
data_y = data_y.reshape(133,12,1)

In [19]:
data_y 

array([[[0.19977261],
        [0.09186396],
        [0.14721013],
        ...,
        [0.12102172],
        [0.        ],
        [0.10010754]],

       [[0.09186396],
        [0.14721013],
        [0.09405303],
        ...,
        [0.        ],
        [0.10010754],
        [0.26186207]],

       [[0.14721013],
        [0.09405303],
        [0.29979003],
        ...,
        [0.10010754],
        [0.26186207],
        [0.14140224]],

       ...,

       [[0.72938174],
        [0.86360998],
        [0.89133784],
        ...,
        [0.65858912],
        [0.60869866],
        [0.55625664]],

       [[0.86360998],
        [0.89133784],
        [0.65131148],
        ...,
        [0.60869866],
        [0.55625664],
        [0.65306548]],

       [[0.89133784],
        [0.65131148],
        [0.72744386],
        ...,
        [0.55625664],
        [0.65306548],
        [0.65942727]]])

In [20]:
data_x_train = data_x[:100,:, :]
data_y_train = data_y[:100,:,:]

data_x_test = data_x[-33:,:, :]
data_y_test = data_y[-33:,:,:]

In [21]:
# print(data_x_train.shape)
# print(data_y_test.shape)
# print(data_x_train.shape)
# print(data_y_test.shape)

In [22]:

#     model = Sequential()
 
#     model.add(LSTM(input_dim=10,output_dim=128,return_sequences=True))
#     model.add(Dropout(0.1))
 
#     model.add(LSTM(128,return_sequences=False))
#     model.add(Dropout(0.1))
 
#     model.add(Dense(output_dim=1))
#     model.add(Activation("linear"))
 
#     model.compile(loss="mse", optimizer="rmsprop")

In [23]:
# model = Sequential()

# model.add(LSTM(output_dim=128, 
#                 input_shape=(10, 1),
#                 activation='relu',
#                 return_sequences=True))
# for i in range(6):
#     model.add(LSTM(output_dim=128,
#                     activation='tanh',
#                     return_sequences=True))
# #     model.add(Dropout(0.1))

# model.add(LSTM(output_dim=1,
#                activation='linear',
#                return_sequences=False))

# model.compile(loss='mse', optimizer='adam', metrics=[metrics.mse])
# model.summary()

In [24]:
def create_model(output_dim1, num_layer, output_dim2):
    model = Sequential()

    model.add(LSTM(output_dim=output_dim1, 
                input_shape=(12, 1),
                activation='relu',
                return_sequences=True))
    for i in range(num_layer):
        model.add(LSTM(output_dim=output_dim2,
                        activation='tanh',
                        return_sequences=True))
#     model.add(Dropout(0.1))

    model.add(Dense(output_dim=1,
               activation='linear'))

    model.compile(loss='mse', optimizer='adam', metrics=[metrics.mse])
#     model.summary()
    return model

In [25]:
# from sklearn.model_selection import RandomizedSearchCV
# from skopt.space import Real, Categorical, Integer
# from keras.wrappers.scikit_learn import KerasRegressor
# from sklearn.model_selection import train_test_split

In [26]:
# #采用暴力搜索，所有参数进行组合，然后选择最好的参数
# tuned_parameters=[{'output_dim1':Integer(28, 128),
#                    'num_layer':Integer(3,12),
#                    'output_dim2':Integer(28, 128)}]
# # 'output_dim1':Integer(28, 128),
# #             'num_layer':Integer(3,12),
# #             'output_dim2':Integer(28, 128)

In [27]:
# train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, train_size=0.80, random_state=0)

In [28]:
# model=KerasRegressor(build_fn=create_model)

In [29]:
# #采用随机搜索，给参数一个范围，然后系统随机选择参数，进行检验，然后选择最好的
# tuned_parameters={'output_dim1':[28, 64, 96,128],
#                    'num_layer':[4,5,6,7,8],
#                    'output_dim2':[28,64, 96,128]}

# lstm=RandomizedSearchCV(model,tuned_parameters,scoring='neg_mean_squared_error',n_iter=10)
 
# lstm.fit(data_x_train,data_y_train)

In [30]:
# print('最优训练器:',lstm.best_estimator_)
# print('最优训练器的精度:',lstm.best_score_)

In [31]:
# best_estimator_ = lstm.best_estimator_

In [32]:
# best_estimator_.predict(data_x_test,batch_size = 1)

In [33]:
# import sklearn
# sorted(sklearn.metrics.SCORERS.keys())

In [34]:
# from sklearn.model_selection import train_test_split
# from skopt import BayesSearchCV
# from skopt.space import Real, Categorical, Integer

In [35]:
# class FixedBayesSearchCV(BayesSearchCV):
#     """
#     Dirty hack to avoid compatibility issues with sklearn 0.2 and skopt.
#     Credit: https://www.kaggle.com/c/home-credit-default-risk/discussion/64004
#     For context, on why the workaround see:
#         - https://github.com/scikit-optimize/scikit-optimize/issues/718
#         - https://github.com/scikit-optimize/scikit-optimize/issues/762
#     """
#     def __init__(self, estimator, search_spaces, optimizer_kwargs=None,
#                 n_iter=50, scoring=None, fit_params=None, n_jobs=1,
#                 n_points=1, iid=True, refit=True, cv=None, verbose=0,
#                 pre_dispatch='2*n_jobs', random_state=None,
#                 error_score='raise', return_train_score=False):
#         """
#         See: https://github.com/scikit-optimize/scikit-optimize/issues/762#issuecomment-493689266
#         """
 
#         # Bug fix: Added this line
#         self.fit_params = fit_params
 
#         self.search_spaces = search_spaces
#         self.n_iter = n_iter
#         self.n_points = n_points
#         self.random_state = random_state
#         self.optimizer_kwargs = optimizer_kwargs
#         self._check_search_space(self.search_spaces)
 
#         # Removed the passing of fit_params to the parent class.
#         super(BayesSearchCV, self).__init__(
#                 estimator=estimator, scoring=scoring, n_jobs=n_jobs, iid=iid,
#                 refit=refit, cv=cv, verbose=verbose, pre_dispatch=pre_dispatch,
#                 error_score=error_score, return_train_score=return_train_score)
 
#     def _run_search(self, x):
#         raise BaseException('Use newer skopt')

In [36]:
# def lstm_auto_para_tuning_bayesian(model,data_x,data_y):
#     train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, train_size=0.80, random_state=0)
#     # cv：交叉验证 n_points：并行采样的超参组数
#     opt = FixedBayesSearchCV(model,cv=5,n_points=2,n_jobs=4,verbose=1,
#         search_spaces={
#             'output_dim1':Integer(28, 128),
#             'num_layer':Integer(3,12),
#             'output_dim2':Integer(28, 128)
#         },
#          fit_params={
#                  'eval_set':[(test_x, test_y)],
#                  'eval_metric': 'mse',
#                  'early_stopping_rounds': 50
#                  })
#     opt.fit(train_x,train_y)
#     print("val. score: %s" % opt.best_score_)
#     print("test score: %s" % opt.score(test_x, test_y))
#     print("Best parameters: ", opt.best_params_)
#     print("Best estimator:", opt.best_estimator_)

In [37]:
model = create_model(32, 4, 32)

Instructions for updating:
Colocations handled automatically by placer.


e:\envs\python36env\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(input_shape=(12, 1), activation="relu", return_sequences=True, units=32)`
  import sys
e:\envs\python36env\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(activation="tanh", return_sequences=True, units=32)`
  # This is added back by InteractiveShellApp.init_path()
e:\envs\python36env\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="linear", units=1)`
  from ipykernel import kernelapp as app


In [38]:
# lstm_auto_para_tuning_bayesian(model,data_x,data_y)

In [39]:
model.fit(data_x_train, data_y_train, epochs=20, batch_size=100, verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/20
100/100 [==============================] - 10s 99ms/step - loss: 0.4384 - mean_squared_error: 0.4384
Epoch 2/20
100/100 [==============================] - 0s 1ms/step - loss: 0.4286 - mean_squared_error: 0.4286
Epoch 3/20
100/100 [==============================] - 0s 1ms/step - loss: 0.4171 - mean_squared_error: 0.4171
Epoch 4/20
100/100 [==============================] - 0s 1ms/step - loss: 0.4043 - mean_squared_error: 0.4043
Epoch 5/20
100/100 [==============================] - 0s 1ms/step - loss: 0.3903 - mean_squared_error: 0.3903
Epoch 6/20
100/100 [==============================] - 0s 1ms/step - loss: 0.3750 - mean_squared_error: 0.3750
Epoch 7/20
100/100 [==============================] - 0s 1ms/step - loss: 0.3582 - mean_squared_error: 0.3582
Epoch 8/20
100/100 [==============================] - 0s 1ms/step - loss: 0.3400 - mean_squared_error: 0.3400
Epoch 9/20
100/100 [==============================] - 0s 1ms/step - lo

In [40]:
# 评估模型,不输出预测结果
loss,accuracy = model.evaluate(data_x_test,data_y_test)
print('\ntest loss','{:.5f}'.format(loss))
print('accuracy','{:.5f}'.format(accuracy))

33/33 [==============================] - 1s 44ms/step

test loss 0.16550
accuracy 0.16550


In [41]:
y_pred = model.predict(data_x_test,batch_size = 1)

In [42]:
y_pred

array([[[0.06110515],
        [0.11219218],
        [0.1729945 ],
        [0.24525452],
        [0.33046326],
        [0.42956242],
        [0.5425567 ],
        [0.66828614],
        [0.80429786],
        [0.9468593 ],
        [1.0914419 ],
        [1.2334404 ]],

       [[0.06110751],
        [0.11220141],
        [0.17301409],
        [0.24523726],
        [0.33032152],
        [0.429112  ],
        [0.5415786 ],
        [0.66655874],
        [0.8015359 ],
        [0.94284016],
        [1.0861549 ],
        [1.2271826 ]],

       [[0.06110682],
        [0.11219613],
        [0.17295071],
        [0.24502267],
        [0.32976696],
        [0.42798832],
        [0.53964454],
        [0.6634931 ],
        [0.7970632 ],
        [0.93689936],
        [1.0790272 ],
        [1.2192943 ]],

       [[0.06110456],
        [0.11214265],
        [0.17275846],
        [0.24450904],
        [0.32870284],
        [0.4261204 ],
        [0.5366206 ],
        [0.65898067],
        [0.7909302 ],
    

In [43]:
# data_y_test[-10:,0]

In [44]:
# data_x_test[-10:,0,-1]

In [45]:
# t = []
# for i in range(2000):
#     if data_y_test[:,0][i]>data_x_test[:,0,-1][i]:
#         t.append(1)
#     else:
#         t.append(0)
# len(t)

In [46]:
# p = []
# for i in range(2000):
#     if y_pred[:,0][i]>data_x_test[:,0,-1][i]:
#         p.append(1)
#     else:
#         p.append(0)
# len(p)

In [47]:
# n = 0
# for i in range(2000):
#     if t[i]==p[i]:
#         n=n+1
# n/2000

In [48]:
data_y_test

array([[[0.72106599],
        [0.5782126 ],
        [0.65889306],
        [0.65519955],
        [0.64346259],
        [0.59414036],
        [0.659587  ],
        [0.76035414],
        [0.67878347],
        [0.44318469],
        [0.52934327],
        [0.42829165]],

       [[0.5782126 ],
        [0.65889306],
        [0.65519955],
        [0.64346259],
        [0.59414036],
        [0.659587  ],
        [0.76035414],
        [0.67878347],
        [0.44318469],
        [0.52934327],
        [0.42829165],
        [0.41449752]],

       [[0.65889306],
        [0.65519955],
        [0.64346259],
        [0.59414036],
        [0.659587  ],
        [0.76035414],
        [0.67878347],
        [0.44318469],
        [0.52934327],
        [0.42829165],
        [0.41449752],
        [0.47848904]],

       [[0.65519955],
        [0.64346259],
        [0.59414036],
        [0.659587  ],
        [0.76035414],
        [0.67878347],
        [0.44318469],
        [0.52934327],
        [0.42829165],
    

In [53]:
data_max = np.max(data_origin)
data_min = np.min(data_origin)
y_pred_to_origin = []
for i in y_pred.reshape(396):
    y = i*(data_max - data_min) + data_min
    y_pred_to_origin.append(y)

In [60]:
len(y_pred_to_origin)

396

In [62]:
y_pred_to_origin = np.array(y_pred_to_origin).reshape(33,12,1)

In [63]:
y_pred_to_origin

array([[[12.17221342],
        [12.93771316],
        [13.84878902],
        [14.93154974],
        [16.20833707],
        [17.69326156],
        [19.38639378],
        [21.27035252],
        [23.30838328],
        [25.44455647],
        [27.61101481],
        [29.73875329]],

       [[12.17224881],
        [12.93785148],
        [13.84908264],
        [14.93129118],
        [16.2062132 ],
        [17.68651218],
        [19.37173752],
        [21.24446873],
        [23.26699744],
        [25.38433274],
        [27.53179421],
        [29.64498539]],

       [[12.17223853],
        [12.93777233],
        [13.84813301],
        [14.92807569],
        [16.19790353],
        [17.6696749 ],
        [19.34275725],
        [21.1985324 ],
        [23.19997699],
        [25.29531451],
        [27.42499019],
        [29.52678504]],

       [[12.1722046 ],
        [12.93697108],
        [13.84525223],
        [14.92037937],
        [16.18195848],
        [17.64168556],
        [19.2974461 ],
     

In [65]:
data_y_test = []
for r in range(12,145):
    for c in range(12):
        item = []
        item.append(data_origin[r+c])
        data_y_test.append(item)
data_y_test = np.array(data_y_test)
print(data_y_test)
print(data_y_test.shape)

[[14.25003836]
 [12.63311045]
 [13.46243023]
 ...
 [19.59167681]
 [21.04228263]
 [21.13760913]]
(1596, 1)


In [68]:
data_y_test = data_y_test.reshape(133,12,1)[-33:,:]

In [69]:
data_y_test

array([[[22.06121774],
        [19.92066993],
        [21.12960442],
        [21.07426005],
        [20.89839063],
        [20.15933505],
        [21.14000262],
        [22.6499205 ],
        [21.42764687],
        [17.89738074],
        [19.18840066],
        [17.67422009]],

       [[19.92066993],
        [21.12960442],
        [21.07426005],
        [20.89839063],
        [20.15933505],
        [21.14000262],
        [22.6499205 ],
        [21.42764687],
        [17.89738074],
        [19.18840066],
        [17.67422009],
        [17.4675257 ]],

       [[21.12960442],
        [21.07426005],
        [20.89839063],
        [20.15933505],
        [21.14000262],
        [22.6499205 ],
        [21.42764687],
        [17.89738074],
        [19.18840066],
        [17.67422009],
        [17.4675257 ],
        [18.42638918]],

       [[21.07426005],
        [20.89839063],
        [20.15933505],
        [21.14000262],
        [22.6499205 ],
        [21.42764687],
        [17.89738074],
     