In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn import preprocessing
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM
from keras.models import Sequential
from keras import metrics

Using TensorFlow backend.
e:\envs\python36env\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
e:\envs\python36env\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
e:\envs\python36env\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
e:\envs\python36env\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning:

In [2]:
data_xls = pd.read_excel('辽宁钢铁行业月用电量.xls')

In [3]:
data_xls

月份  辽宁钢铁行业月用电量（亿千万时）    钢铁产量   汽车产量      水泥产量  金属切削机床   大中型拖拉机  \
0    2007M01         13.856687  354.62  78.72   8370.22    4.12  14440.0   
1    2007M02         11.941298  318.87  59.65   6500.82    3.35  13941.0   
2    2007M03         14.555307  368.91  88.96   9308.57    4.78  26231.0   
3    2007M04         13.656541  366.22  83.98  11643.56    5.41  22263.0   
4    2007M05         13.143799  374.81  74.35  12869.06    5.34  14824.0   
..       ...               ...     ...    ...       ...     ...      ...   
153  2019M10         19.591677  609.31    NaN       NaN     NaN      NaN   
154  2019M11         21.042283  630.76    NaN       NaN     NaN      NaN   
155  2019M12         21.137609  648.00    NaN       NaN     NaN      NaN   
156  2020M01         22.502425  621.00    NaN       NaN     NaN      NaN   
157  2020M02         19.675281  525.78    NaN       NaN     NaN      NaN   

      鞍钢股价   本钢股价   凌钢股价  
0    12.95   6.50   6.10  
1    12.87   8.09   7.58  
2    14.57   8.55   8.28  
3    17.64  13.35  11.03  
4    18.34  13.89  10.44  
..     ...    ...    ...  
153    NaN    NaN    NaN  
154    NaN    NaN    NaN  
155    NaN    NaN    NaN  
156    NaN    NaN    NaN  
157    NaN    NaN    NaN  

[158 rows x 10 columns]

In [4]:
# data_xls.drop(['月份'，], axis=1, inplace=True)
# data_xls

In [5]:
data_origin = np.array(data_xls)[:84,:]
print(data_origin)

[['2007M01' 13.85668698 354.62 78.72 8370.22 4.12 14440.0 12.95 6.5 6.1]
 ['2007M02' 11.94129775 318.87 59.65 6500.82 3.35 13941.0 12.87 8.09 7.58]
 ['2007M03' 14.5553069 368.91 88.96 9308.57 4.78 26231.0 14.57 8.55 8.28]
 ['2007M04' 13.65654085 366.22 83.98 11643.56 5.41 22263.0 17.64 13.35
  11.03]
 ['2007M05' 13.14379943 374.81 74.35 12869.06 5.34 14824.0 18.34 13.89
  10.44]
 ['2007M06' 13.89728023 407.8 75.92 12733.27 5.51 12109.0 17.69 9.15 9.33]
 ['2007M07' 13.82012254 371.56 67.88 11748.24 5.27 15355.0 23.97 13.97
  11.03]
 ['2007M08' 13.79591637 347.4 66.14 12081.19 5.31 17835.0 34.4 14.38 13.3]
 ['2007M09' 13.98148773 371.86 78.3 12520.21 5.73 21170.0 36.0 15.59
  14.25]
 ['2007M10' 13.27588781 358.27 75.17 12379.76 5.3 13127.0 31.21 14.0
  12.45]
 ['2007M11' 13.96807882 345.8 86.52 12547.31 5.24 11773.0 24.44 13.18
  10.91]
 ['2007M12' 14.28233571 369.6 84.87 12328.41 5.06 17212.0 30.18 14.7
  13.45]
 ['2008M01' 14.25003836 336.4 84.3 8268.01 5.07 19463.0 22.36 13.29 13.45]


In [6]:
data_y_origin = data_origin[:,9]
data_y_origin

array([6.1, 7.58, 8.28, 11.03, 10.44, 9.33, 11.03, 13.3, 14.25, 12.45,
       10.91, 13.45, 13.45, 13.45, 12.7, 11.18, 14.45, 10.42, 9.02, 6.32,
       6.49, 3.72, 5.03, 4.43, 5.52, 5.04, 6.58, 6.97, 7.73, 9.03, 13.59,
       9.22, 8.07, 9.94, 12.34, 13.02, 10.14, 11.0, 11.53, 9.12, 7.09,
       5.82, 7.24, 7.58, 7.92, 9.67, 8.58, 8.71, 9.56, 10.47, 10.4, 9.6,
       8.55, 9.12, 8.49, 8.21, 6.59, 6.94, 6.13, 5.49, 5.34, 6.06, 5.15,
       5.01, 5.57, 4.65, 3.85, 3.67, 3.71, 3.86, 3.69, 4.75, 4.44, 4.33,
       4.83, 3.71, 3.88, 3.16, 3.03, 3.31, 3.28, 3.24, 3.35, 3.22],
      dtype=object)

In [7]:
data_x_origin = np.delete(data_origin,[0,6,7,8], axis = 1)
print(data_x_origin)

[[13.85668698 354.62 78.72 8370.22 4.12 6.1]
 [11.94129775 318.87 59.65 6500.82 3.35 7.58]
 [14.5553069 368.91 88.96 9308.57 4.78 8.28]
 [13.65654085 366.22 83.98 11643.56 5.41 11.03]
 [13.14379943 374.81 74.35 12869.06 5.34 10.44]
 [13.89728023 407.8 75.92 12733.27 5.51 9.33]
 [13.82012254 371.56 67.88 11748.24 5.27 11.03]
 [13.79591637 347.4 66.14 12081.19 5.31 13.3]
 [13.98148773 371.86 78.3 12520.21 5.73 14.25]
 [13.27588781 358.27 75.17 12379.76 5.3 12.45]
 [13.96807882 345.8 86.52 12547.31 5.24 10.91]
 [14.28233571 369.6 84.87 12328.41 5.06 13.45]
 [14.25003836 336.4 84.3 8268.01 5.07 13.45]
 [12.63311045 335.34 67.21 5958.28 4.69 13.45]
 [13.46243023 366.4 106.57 11322.94 5.85 12.7]
 [12.66591199 343.26 100.41 12488.42 6.03 11.18]
 [15.74872233 399.75 89.49 13198.24 7.13 14.45]
 [13.96355619 409.85 86.42 13181.24 5.89 10.42]
 [14.0412472 380.07 75.72 11943.23 5.4 9.02]
 [14.73483898 372.28 62.58 11985.87 5.31 6.32]
 [14.43095576 355.84 79.18 12422.85 5.11 6.49]
 [13.07001702 323

In [8]:
print(data_x_origin.shape)

(84, 6)


In [9]:
# #Max-Min标准化
# #建立MinMaxScaler对象
scaler = preprocessing.MinMaxScaler()

# # 标准化处理
# scaler = preprocessing.StandardScaler()
data_x = data_x_origin
data_x[:,0] = scaler.fit_transform(data_x_origin[:,0].reshape(-1, 1)).reshape(84)
data_x[:,1] = scaler.fit_transform(data_x_origin[:,1].reshape(-1, 1)).reshape(84)
data_x[:,2] = scaler.fit_transform(data_x_origin[:,2].reshape(-1, 1)).reshape(84)
data_x[:,3] = scaler.fit_transform(data_x_origin[:,3].reshape(-1, 1)).reshape(84)
data_x[:,4] = scaler.fit_transform(data_x_origin[:,4].reshape(-1, 1)).reshape(84)
data_x[:,5] = scaler.fit_transform(data_x_origin[:,5].reshape(-1, 1)).reshape(84)
data_y = scaler.fit_transform(data_y_origin.reshape(-1, 1))

In [10]:
# n = 0
# for i in range(data.shape[0]):
#     if data[i,0]<0:
#         n=n+1
# print(n)

In [11]:
print(data_x.shape)
print(data_y.shape)

(84, 6)
(84, 1)


In [12]:
# data.shape

In [13]:
# data_x = data[:,0]

In [14]:
# data_y = data[:,1]

In [15]:
# data_y = data[-146:,:]
# print(data_y.shape)

In [16]:
# data_x = []
# for r in range(146):
#     for c in range(12):
#         item = []
#         item.append(data[r+c, 0])
#         data_x.append(item)
# data_x = np.array(data_x)
# print(data_x)
# print(data_x.shape)

In [17]:
# data_x=data_x.reshape(84,1,1)

In [18]:
# data_x.shape

In [19]:
# data_x

In [20]:
# data_y = data_y.reshape(84,1,1)

In [21]:
data_x_train = data_x[:70,:]
data_y_train = data_y[:70,:]

data_x_test = data_x[-14:,:]
data_y_test = data_y[-14:,:]

In [22]:
print(data_x_train.shape)
print(data_y_train.shape)
print(data_x_test.shape)
print(data_y_test.shape)

(70, 6)
(70, 1)
(14, 6)
(14, 1)


In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(data_x_train, data_y_train, test_size=0.2, random_state=520)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(56, 6)
(56, 1)
(14, 6)
(14, 1)


In [25]:

#     model = Sequential()
 
#     model.add(LSTM(input_dim=10,output_dim=128,return_sequences=True))
#     model.add(Dropout(0.1))
 
#     model.add(LSTM(128,return_sequences=False))
#     model.add(Dropout(0.1))
 
#     model.add(Dense(output_dim=1))
#     model.add(Activation("linear"))
 
#     model.compile(loss="mse", optimizer="rmsprop")

In [26]:
# model = Sequential()

# model.add(LSTM(output_dim=128, 
#                 input_shape=(10, 1),
#                 activation='relu',
#                 return_sequences=True))
# for i in range(6):
#     model.add(LSTM(output_dim=128,
#                     activation='tanh',
#                     return_sequences=True))
# #     model.add(Dropout(0.1))

# model.add(LSTM(output_dim=1,
#                activation='linear',
#                return_sequences=False))

# model.compile(loss='mse', optimizer='adam', metrics=[metrics.mse])
# model.summary()

In [27]:
# def create_model(output_dim1, num_layer, output_dim2):
#     model = Sequential()

#     model.add(LSTM(output_dim=output_dim1, 
#                 input_shape=(1, 1),
#                 activation='relu',
#                 return_sequences=True))
#     for i in range(num_layer):
#         model.add(LSTM(output_dim=output_dim2,
#                         activation='tanh',
#                         return_sequences=True))
# #     model.add(Dropout(0.1))

#     model.add(LSTM(output_dim=1,
#                activation='tanh',
#                 return_sequences=False))

#     model.compile(loss='mse', optimizer='adam', metrics=[metrics.mse])
# #     model.summary()
#     return model

In [28]:
# from sklearn.model_selection import RandomizedSearchCV
# from skopt.space import Real, Categorical, Integer
# from keras.wrappers.scikit_learn import KerasRegressor
# # from sklearn.model_selection import train_test_split

In [29]:
# #采用暴力搜索，所有参数进行组合，然后选择最好的参数
# tuned_parameters=[{'output_dim1':Integer(28, 128),
#                    'num_layer':Integer(3,12),
#                    'output_dim2':Integer(28, 128)}]
# # 'output_dim1':Integer(28, 128),
# #             'num_layer':Integer(3,12),
# #             'output_dim2':Integer(28, 128)

In [30]:
# train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, train_size=0.80, random_state=0)

In [31]:
# model=KerasRegressor(build_fn=create_model)

In [32]:
# #采用随机搜索，给参数一个范围，然后系统随机选择参数，进行检验，然后选择最好的
# tuned_parameters={'output_dim1':[28, 64, 96,128],
#                    'num_layer':[4,5,6,7,8],
#                    'output_dim2':[28,64, 96,128]}

# lstm=RandomizedSearchCV(model,tuned_parameters,scoring='neg_mean_squared_error',n_iter=10)
 
# lstm.fit(data_x_train,data_y_train)

In [33]:
# print('最优训练器:',lstm.best_estimator_)
# print('最优训练器的精度:',lstm.best_score_)

In [34]:
# best_estimator_ = lstm.best_estimator_

In [35]:
# best_estimator_.predict(data_x_test,batch_size = 1)

In [36]:
# import sklearn
# sorted(sklearn.metrics.SCORERS.keys())

In [37]:
# from sklearn.model_selection import train_test_split
# from skopt import BayesSearchCV
# from skopt.space import Real, Categorical, Integer

In [38]:
# class FixedBayesSearchCV(BayesSearchCV):
#     """
#     Dirty hack to avoid compatibility issues with sklearn 0.2 and skopt.
#     Credit: https://www.kaggle.com/c/home-credit-default-risk/discussion/64004
#     For context, on why the workaround see:
#         - https://github.com/scikit-optimize/scikit-optimize/issues/718
#         - https://github.com/scikit-optimize/scikit-optimize/issues/762
#     """
#     def __init__(self, estimator, search_spaces, optimizer_kwargs=None,
#                 n_iter=50, scoring=None, fit_params=None, n_jobs=1,
#                 n_points=1, iid=True, refit=True, cv=None, verbose=0,
#                 pre_dispatch='2*n_jobs', random_state=None,
#                 error_score='raise', return_train_score=False):
#         """
#         See: https://github.com/scikit-optimize/scikit-optimize/issues/762#issuecomment-493689266
#         """
 
#         # Bug fix: Added this line
#         self.fit_params = fit_params
 
#         self.search_spaces = search_spaces
#         self.n_iter = n_iter
#         self.n_points = n_points
#         self.random_state = random_state
#         self.optimizer_kwargs = optimizer_kwargs
#         self._check_search_space(self.search_spaces)
 
#         # Removed the passing of fit_params to the parent class.
#         super(BayesSearchCV, self).__init__(
#                 estimator=estimator, scoring=scoring, n_jobs=n_jobs, iid=iid,
#                 refit=refit, cv=cv, verbose=verbose, pre_dispatch=pre_dispatch,
#                 error_score=error_score, return_train_score=return_train_score)
 
#     def _run_search(self, x):
#         raise BaseException('Use newer skopt')

In [39]:
# def lstm_auto_para_tuning_bayesian(model,data_x,data_y):
#     train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, train_size=0.80, random_state=0)
#     # cv：交叉验证 n_points：并行采样的超参组数
# #     model=KerasRegressor(build_fn=create_model)
#     opt = FixedBayesSearchCV(model,cv=5,n_points=2,n_jobs=4,verbose=1,
#         search_spaces={
#             'output_dim1':Integer(12, 48),
#             'num_layer':Integer(3,12),
#             'output_dim2':Integer(12, 48)
#         },
#          fit_params={
#                  'eval_set':[(test_x[:,0,0], test_y[:,0,0])],
#                  'eval_metric': 'mse',
#                  'early_stopping_rounds': 50
#                  })
#     opt.fit(train_x,train_y)
#     print("val. score: %s" % opt.best_score_)
#     print("test score: %s" % opt.score(test_x, test_y))
#     print("Best parameters: ", opt.best_params_)
#     print("Best estimator:", opt.best_estimator_)

In [40]:
# model=KerasRegressor(build_fn=create_model)

In [41]:
# lstm_auto_para_tuning_bayesian(model,data_x,data_y)

In [42]:
# model = create_model(24, 4, 24)

In [43]:
# lstm_auto_para_tuning_bayesian(model,data_x,data_y)

In [44]:
model = Sequential()
model.add(Dense(6, activation='relu',input_shape=(X_train.shape[1],)))
model.add(Dense(6, activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer = 'sgd',# 还可以通过optimizer = optimizers.RMSprop(lr=0.001)来为优化器指定参数.optimizer='rmsprop'
              loss='mean_squared_error', # 等价于loss = losses.binary_crossentropy
              metrics=['mse']) # 等价于metrics = [metircs.binary_accuracy]
model.fit(X_train, Y_train,epochs=80, batch_size=20, verbose=0, validation_data=(X_test,Y_test))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [45]:
model.evaluate(X_test,Y_test)

14/14 [==============================] - 0s 142us/step


[0.06811218708753586, 0.06811218708753586]

In [46]:
# model.fit(data_x_train, data_y_train, epochs=20, batch_size=20, verbose=1)

In [47]:
# 评估模型,不输出预测结果
loss,accuracy = model.evaluate(X_test,Y_test)
print('\ntest loss','{:.5f}'.format(loss))
print('accuracy','{:.5f}'.format(accuracy))

14/14 [==============================] - 0s 143us/step

test loss 0.06811
accuracy 0.06811


In [48]:
y_pred = model.predict(data_x_test,batch_size = 1)

In [49]:
y_pred

array([[0.409288  ],
       [0.44375923],
       [0.5003203 ],
       [0.51315963],
       [0.50066876],
       [0.4270532 ],
       [0.40591213],
       [0.4172614 ],
       [0.41766876],
       [0.41197392],
       [0.43555093],
       [0.44464248],
       [0.48870987],
       [0.48751017]], dtype=float32)

In [50]:
# data_y_test[-10:,0]

In [51]:
# data_x_test[-10:,0,-1]

In [52]:
# t = []
# for i in range(2000):
#     if data_y_test[:,0][i]>data_x_test[:,0,-1][i]:
#         t.append(1)
#     else:
#         t.append(0)
# len(t)

In [53]:
# p = []
# for i in range(2000):
#     if y_pred[:,0][i]>data_x_test[:,0,-1][i]:
#         p.append(1)
#     else:
#         p.append(0)
# len(p)

In [54]:
# n = 0
# for i in range(2000):
#     if t[i]==p[i]:
#         n=n+1
# n/2000

In [55]:
# data.shape

In [56]:
data_y_max = np.max(data_y_origin)

In [57]:
data_y_min = np.min(data_y_origin)

In [58]:
data_y_max

14.45

In [59]:
data_y_min 

3.03

In [60]:
y_test_origin = data_y_origin[-14:]

In [61]:
y_test_origin

array([3.69, 4.75, 4.44, 4.33, 4.83, 3.71, 3.88, 3.16, 3.03, 3.31, 3.28,
       3.24, 3.35, 3.22], dtype=object)

In [62]:
y_pred_to_origin = []
for i in y_pred:
    y = i*(data_y_max - data_y_min) + data_y_min
    y_pred_to_origin.append(y)

In [63]:
y_pred_to_origin

[array([7.704069], dtype=float32),
 array([8.097731], dtype=float32),
 array([8.743658], dtype=float32),
 array([8.890283], dtype=float32),
 array([8.747638], dtype=float32),
 array([7.906948], dtype=float32),
 array([7.665517], dtype=float32),
 array([7.795125], dtype=float32),
 array([7.799777], dtype=float32),
 array([7.734742], dtype=float32),
 array([8.003991], dtype=float32),
 array([8.107818], dtype=float32),
 array([8.611067], dtype=float32),
 array([8.597366], dtype=float32)]